services:
  app:
    image: luftdaten/api:staging
    restart: unless-stopped
    command: /bin/sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 80 --reload & (python download_csv.py && python import_from_csv.py)"
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.luftdaten-api-staging.entrypoints=https"
      - "traefik.http.routers.luftdaten-api-staging.rule=(Host(`staging.api.luftdaten.at`))"
      - "traefik.http.routers.luftdaten-api-staging.tls=true"
      - "traefik.http.routers.luftdaten-api-staging.tls.certresolver=http"
      - "traefik.http.routers.luftdaten-api-staging.service=luftdaten-api-staging"
      - "traefik.http.services.luftdaten-api-staging.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.luftdaten-api-staging.middlewares=default@file"
#      - "com.centurylinklabs.watchtower.enable=true" # Hiermit wird dieser Service explizit automatisiert aktualisiert.
    networks:
      - default
      - proxy
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./sensor_community_archive:/usr/src/app/sensor_community_archive
  db:
    image: postgres:16
    networks:
      - default
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
  admin:
    image: dpage/pgadmin4:latest
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./pgadmin-data/:/var/lib/pgadmin/
    labels:  
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.luftdaten-api-staging-admin.entrypoints=https"
      - "traefik.http.routers.luftdaten-api-staging-admin.rule=Host(`admin.staging.api.luftdaten.at`)"
      - "traefik.http.routers.luftdaten-api-staging-admin.tls=true"
      - "traefik.http.routers.luftdaten-api-staging-admin.tls.certresolver=http"
      - "traefik.http.routers.luftdaten-api-staging-admin.service=luftdaten-api-staging-admin"
      - "traefik.http.services.luftdaten-api-staging-admin.loadbalancer.server.port=80"
      - "traefik.http.routers.luftdaten-api-staging-admin.middlewares=default@file"
      - "com.centurylinklabs.watchtower.enable=true" # Hiermit wird dieser Service explizit automatisiert aktualisiert.
    networks:
      - proxy
      - default

volumes:
  postgres_data:  

networks:
  default:
  proxy:
    external: true
