"""test exclude view

Revision ID: 06c69449c7d0
Revises: 8e1c45de1275
Create Date: 2024-11-08 13:00:41.414103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '06c69449c7d0'
down_revision: Union[str, None] = '8e1c45de1275'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stationStatus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stationStatus_id'), 'stationStatus', ['id'], unique=False)
    op.drop_index('ix_StationStatus_id', table_name='StationStatus')
    op.drop_table('StationStatus')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('StationStatus',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('station_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], name='StationStatus_station_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='StationStatus_pkey')
    )
    op.create_index('ix_StationStatus_id', 'StationStatus', ['id'], unique=False)
    op.drop_index(op.f('ix_stationStatus_id'), table_name='stationStatus')
    op.drop_table('stationStatus')
    # ### end Alembic commands ###
