"""Add source column to stations

Revision ID: 0ab739389abd
Revises: 2dcba7bf5523
Create Date: 2024-10-06 17:21:30.561934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ab739389abd'
down_revision: Union[str, None] = '2dcba7bf5523'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stations', sa.Column('source', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stations', 'source')
    # ### end Alembic commands ###
