"""add tz to City

Revision ID: 2dcba7bf5523
Revises: a44ff1a4c716
Create Date: 2024-10-05 17:47:44.650879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dcba7bf5523'
down_revision: Union[str, None] = 'a44ff1a4c716'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('tz', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cities', 'tz')
    # ### end Alembic commands ###
