"""Removed Houryl avg table

Revision ID: 2df6cd6bb99c
Revises: 06c69449c7d0
Create Date: 2024-11-11 10:04:01.570495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2df6cd6bb99c'
down_revision: Union[str, None] = '06c69449c7d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_hourly_averages_id', table_name='hourly_averages')
    op.drop_table('hourly_averages')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hourly_averages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('station_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('avg_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sensor_model', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dimension', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], name='hourly_averages_station_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='hourly_averages_pkey')
    )
    op.create_index('ix_hourly_averages_id', 'hourly_averages', ['id'], unique=False)
    # ### end Alembic commands ###
