"""Update station model

Revision ID: 5661cd0d79fd
Revises: e504efb70842
Create Date: 2024-09-27 13:00:46.043884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5661cd0d79fd'
down_revision: Union[str, None] = 'e504efb70842'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurements', sa.Column('time_received', sa.DateTime(), nullable=True))
    op.add_column('measurements', sa.Column('time_measured', sa.DateTime(), nullable=True))
    op.add_column('stations', sa.Column('firmware', sa.String(), nullable=True))
    op.add_column('stations', sa.Column('last_active', sa.DateTime(), nullable=True))
    op.drop_column('stations', 'time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stations', sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('stations', 'last_active')
    op.drop_column('stations', 'firmware')
    op.drop_column('measurements', 'time_measured')
    op.drop_column('measurements', 'time_received')
    # ### end Alembic commands ###
