"""added cascade to all fks

Revision ID: 5826b05428eb
Revises: a344b0c7bf56
Create Date: 2025-01-22 14:46:33.823214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5826b05428eb'
down_revision: Union[str, None] = 'a344b0c7bf56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cities_country_id_fkey', 'cities', type_='foreignkey')
    op.create_foreign_key(None, 'cities', 'countries', ['country_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('locations_country_id_fkey', 'locations', type_='foreignkey')
    op.drop_constraint('locations_city_id_fkey', 'locations', type_='foreignkey')
    op.create_foreign_key(None, 'locations', 'countries', ['country_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'locations', 'cities', ['city_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('measurements_location_id_fkey', 'measurements', type_='foreignkey')
    op.drop_constraint('measurements_station_id_fkey', 'measurements', type_='foreignkey')
    op.create_foreign_key(None, 'measurements', 'stations', ['station_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'measurements', 'locations', ['location_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('stationStatus_station_id_fkey', 'stationStatus', type_='foreignkey')
    op.create_foreign_key(None, 'stationStatus', 'stations', ['station_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('stations_location_id_fkey', 'stations', type_='foreignkey')
    op.create_foreign_key(None, 'stations', 'locations', ['location_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('values_measurement_id_fkey', 'values', type_='foreignkey')
    op.create_foreign_key(None, 'values', 'measurements', ['measurement_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'values', type_='foreignkey')
    op.create_foreign_key('values_measurement_id_fkey', 'values', 'measurements', ['measurement_id'], ['id'])
    op.drop_constraint(None, 'stations', type_='foreignkey')
    op.create_foreign_key('stations_location_id_fkey', 'stations', 'locations', ['location_id'], ['id'])
    op.drop_constraint(None, 'stationStatus', type_='foreignkey')
    op.create_foreign_key('stationStatus_station_id_fkey', 'stationStatus', 'stations', ['station_id'], ['id'])
    op.drop_constraint(None, 'measurements', type_='foreignkey')
    op.drop_constraint(None, 'measurements', type_='foreignkey')
    op.create_foreign_key('measurements_station_id_fkey', 'measurements', 'stations', ['station_id'], ['id'])
    op.create_foreign_key('measurements_location_id_fkey', 'measurements', 'locations', ['location_id'], ['id'])
    op.drop_constraint(None, 'locations', type_='foreignkey')
    op.drop_constraint(None, 'locations', type_='foreignkey')
    op.create_foreign_key('locations_city_id_fkey', 'locations', 'cities', ['city_id'], ['id'])
    op.create_foreign_key('locations_country_id_fkey', 'locations', 'countries', ['country_id'], ['id'])
    op.drop_constraint(None, 'cities', type_='foreignkey')
    op.create_foreign_key('cities_country_id_fkey', 'cities', 'countries', ['country_id'], ['id'])
    # ### end Alembic commands ###
