"""CalibrationMeasurement added relationships

Revision ID: a0593613bf91
Revises: fc8c3d3efd58
Create Date: 2025-02-24 14:37:56.645678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0593613bf91'
down_revision: Union[str, None] = 'fc8c3d3efd58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('values', sa.Column('calibration_measurement_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'values', 'calibration_measurements', ['calibration_measurement_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'values', type_='foreignkey')
    op.drop_column('values', 'calibration_measurement_id')
    # ### end Alembic commands ###
