"""add slug to City and Country

Revision ID: a44ff1a4c716
Revises: dab145493248
Create Date: 2024-10-05 15:55:11.117312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a44ff1a4c716'
down_revision: Union[str, None] = 'dab145493248'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('slug', sa.String(), nullable=True))
    op.create_index(op.f('ix_cities_slug'), 'cities', ['slug'], unique=True)
    op.add_column('countries', sa.Column('slug', sa.String(), nullable=True))
    op.create_index(op.f('ix_countries_slug'), 'countries', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_countries_slug'), table_name='countries')
    op.drop_column('countries', 'slug')
    op.drop_index(op.f('ix_cities_slug'), table_name='cities')
    op.drop_column('cities', 'slug')
    # ### end Alembic commands ###
