"""Added CalibrationMeasurement Table

Revision ID: fc8c3d3efd58
Revises: 80277768fe1d
Create Date: 2025-02-24 14:30:44.766046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc8c3d3efd58'
down_revision: Union[str, None] = '80277768fe1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calibration_measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_received', sa.DateTime(), nullable=True),
    sa.Column('time_measured', sa.DateTime(), nullable=True),
    sa.Column('sensor_model', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calibration_measurements_id'), 'calibration_measurements', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calibration_measurements_id'), table_name='calibration_measurements')
    op.drop_table('calibration_measurements')
    # ### end Alembic commands ###
